; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#define MyAppDir  "C:\Users\tmontgomery\Documents\Visual Studio 2015\Projects\qta\qw_test_project\qw_test\bin\Debug"
; Ryans dir = #define MyAppDir  "\\psf\Home\Documents\Visual Studio 2015\Projects\qta\qw_test_project\qw_test\bin\Debug"
#define MyAppName "ConnectTax Avalara for QuoteWerks"
#define MyAppVersion "2.1"
#define MyAppPublisher "Greystone Technology"
#define MyAppURL "https://www.ConnectTax.com"
#define MyAppExeName "ConnectTaxQW.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{7C613E37-1FAA-424D-8252-BFE808E2D6E3}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
DisableDirPage=no
OutputBaseFilename=Avalara_QW_Setup
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "{#MyAppDir}\ConnectTaxQW.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppDir}\Avalara.AvaTax.Adapter.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppDir}\settings.ini"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppDir}\Avalara for QuoteWerks - Setup Guide.pdf"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppDir}\Newtonsoft.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}"; Filename: "{#MyAppURL}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"

[Run]
Filename: "{app}\Avalara for QuoteWerks - Setup Guide.pdf"; Flags: shellexec postinstall nowait

[Messages]
FinishedLabel=Follow the Setup Guide included in the installation directory to complete the configuration within QuoteWerks.